import SwiftUI
import Photos

struct OnboardingScreen: View {
    let onComplete: () -> Void

    @State private var page: Int = 0
    @State private var opacity: Double = 0

    var body: some View {
        ZStack(alignment: .bottom) {
            Color.appBackground.ignoresSafeArea()

            // ── 페이드 대상 콘텐츠 ──
            ZStack(alignment: .bottom) {
                // 일러스트 영역 (스텝 레이블)
                VStack(spacing: 0) {
                    HStack {
                        Text(page == 0 ? "(1) b-cuts    → →     film" : "(2) film      → →      cassette")
                            .font(.cutiveMono(20))
                            .foregroundColor(.appBlack)
                        Spacer()
                    }
                    .padding(.horizontal, 24)
                    .padding(.top, 64)

                    Spacer()
                }

                // 일러스트 이미지
                Image(page == 0 ? "onboarding_asset_1" : "onboarding_asset_2")
                    .resizable()
                    .scaledToFit()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .ignoresSafeArea()

                // 하단 패널 + 버튼
                VStack(spacing: 0) {
                    HStack {
                        Button { exit(0) } label: {
                            Text("exit")
                                .font(.cutiveMono(16))
                                .foregroundColor(.appBlack)
                        }

                        Spacer()

                        Button { handleAllow() } label: {
                            Text("allow")
                                .font(.cutiveMono(16))
                                .foregroundColor(.appAccent)
                        }
                    }
                    .padding(.horizontal, 24)
                    .padding(.bottom, 12)

                    OnboardingInfoPanel(page: page)
                        .padding(.bottom, 40)
                }
            }
            .opacity(opacity)
        }
        .navigationBarHidden(true)
        .onAppear {
            withAnimation(.easeIn(duration: 0.5)) { opacity = 1 }
        }
    }

    private func handleAllow() {
        if page == 0 {
            PHPhotoLibrary.requestAuthorization(for: .readWrite) { _ in
                DispatchQueue.main.async {
                    withAnimation(.easeOut(duration: 0.25)) { opacity = 0 }
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) {
                        page = 1
                        withAnimation(.easeIn(duration: 0.5)) { opacity = 1 }
                    }
                }
            }
        } else {
            onComplete()
        }
    }
}

// MARK: - 온보딩 정보 패널

struct OnboardingInfoPanel: View {
    let page: Int

    var body: some View {
        VStack(alignment: .trailing, spacing: 8) {
            if page == 0 {
                Text("films")
                    .font(.cutiveMono(24))
                    .foregroundColor(.appBlack)
                Text("made out of your b-cuts")
                    .font(.cutiveMono(16))
                    .foregroundColor(.appBlack)
                Text("ask permission of managing photos")
                    .font(.cutiveMono(16))
                    .foregroundColor(.appBlack)
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)
            } else {
                Text("cassette musics")
                    .font(.cutiveMono(24))
                    .foregroundColor(.appBlack)
                Text("are generated by ai with film")
                    .font(.cutiveMono(16))
                    .foregroundColor(.appBlack)
                Text("ask permission of ai usage")
                    .font(.cutiveMono(16))
                    .foregroundColor(.appBlack)
            }

            Text("learn more")
                .font(.cutiveMono(13))
                .foregroundColor(.appDarkGray)
                .padding(.top, 4)
        }
        .padding(.top, 14)
        .padding(.horizontal, 16)
        .frame(width: 345, height: 140, alignment: .topTrailing)
        .background(Color.appWhite)
        .overlay(Rectangle().stroke(Color.appBlack, lineWidth: 1))
    }
}

#Preview {
    OnboardingScreen(onComplete: {})
}
