import SwiftUI
import Photos

struct OnboardingScreen: View {
    let onComplete: () -> Void

    @State private var page: Int = 0
    @State private var opacity: Double = 0

    var body: some View {
        ZStack(alignment: .bottom) {
            Color.appBackground.ignoresSafeArea()

            // ── 페이드 대상 콘텐츠 ──
            ZStack(alignment: .bottom) {
                // 일러스트 영역 (스텝 레이블)
                VStack(spacing: 0) {
                    HStack {
                        Text(page == 0 ? "(1) b-cuts    → →     film" : "(2) film      → →      cassette")
                            .font(.appTitle)
                            .foregroundColor(.appBlack)
                        Spacer()
                    }
                    .padding(.horizontal, 24)
                    .padding(.top, 64)

                    Spacer()
                }

                // 일러스트 이미지
                Image(page == 0 ? "onboarding_asset_1" : "onboarding_asset_2")
                    .resizable()
                    .scaledToFit()
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .ignoresSafeArea()

                // 하단 패널 + 버튼
                VStack(spacing: 0) {
                    HStack {
                        Button { exit(0) } label: {
                            Text("exit")
                                .font(.appBody)
                                .foregroundColor(.appBlack)
                        }

                        Spacer()

                        Button { handleAllow() } label: {
                            Text("allow")
                                .font(.appBody)
                                .foregroundColor(.appAccent)
                        }
                    }
                    .padding(.horizontal, 24)
                    .padding(.bottom, 12)

                    OnboardingInfoPanel(page: page)
                        .padding(.bottom, 40)
                }
            }
            .opacity(opacity)
        }
        .navigationBarHidden(true)
        .onAppear {
            withAnimation(.easeIn(duration: 0.5)) { opacity = 1 }
        }
    }

    private func handleAllow() {
        if page == 0 {
            PHPhotoLibrary.requestAuthorization(for: .readWrite) { _ in
                DispatchQueue.main.async {
                    withAnimation(.easeOut(duration: 0.25)) { opacity = 0 }
                    DispatchQueue.main.asyncAfter(deadline: .now() + 0.25) {
                        page = 1
                        withAnimation(.easeIn(duration: 0.5)) { opacity = 1 }
                    }
                }
            }
        } else {
            onComplete()
        }
    }
}

// MARK: - 온보딩 정보 패널

struct OnboardingInfoPanel: View {
    let page: Int

    private var isKorean: Bool {
        Locale.current.language.languageCode?.identifier == "ko"
    }

    private var learnMoreURL: URL {
        if page == 0 {
            let str = isKorean
                ? "https://polydactyl-alder-784.notion.site/3821d0eacd8f805cbc5acd1d34118336"
                : "https://polydactyl-alder-784.notion.site/Photos-Access-3821d0eacd8f8033acbdc5ba3ac99781"
            return URL(string: str)!
        } else {
            let str = isKorean
                ? "https://polydactyl-alder-784.notion.site/AI-3821d0eacd8f80378da2fc79678b0258"
                : "https://polydactyl-alder-784.notion.site/AI-Music-Generation-3821d0eacd8f801b9b1bee3dfb082854"
            return URL(string: str)!
        }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            if page == 0 {
                Text("films")
                    .font(.appHeader)
                    .foregroundColor(.appBlack)
                    .frame(height: 30)
                Text("made out of your b-cuts")
                    .font(.appBody)
                    .foregroundColor(.appBlack)
                    .frame(height: 23)
                Text("ask permission of managing photos")
                    .font(.appBody)
                    .foregroundColor(.appBlack)
                    .frame(height: 23)
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)
            } else {
                Text("cassette musics")
                    .font(.appHeader)
                    .foregroundColor(.appBlack)
                    .frame(height: 30)
                Text("are generated by ai with film")
                    .font(.appBody)
                    .foregroundColor(.appBlack)
                    .frame(height: 23)
                Text("ask permission of ai usage")
                    .font(.appBody)
                    .foregroundColor(.appBlack)
                    .frame(height: 23)
            }

            Link("learn more", destination: learnMoreURL)
                .font(.custom("SF Mono", size: 13).monospaced())
                .kerning(13 * 0.08)
                .foregroundColor(.appDarkGray)
                .underline()
                .frame(height: 23)
        }
        .padding(.top, 12)
        .padding(.horizontal, 16)
        .frame(width: 345, height: 140, alignment: .topLeading)
        .background(Color.appWhite)
        .overlay(Rectangle().stroke(Color.appBlack, lineWidth: 1))
    }
}

#Preview {
    OnboardingScreen(onComplete: {})
}
